env:
  browser: true
  es2021: true
extends:
- next
- eslint:recommended
- plugin:react/recommended
- plugin:@typescript-eslint/recommended
- prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  quotes:
  - 2
  - single
  - avoid-escape
  no-tabs:
  - error
  - allowIndentationTabs: true
  spaced-comment:
  - error
  - always
  - markers:
    - "/"
  no-unused-vars: 'off'
  "@typescript-eslint/no-unused-vars": 'off'
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
  - warn
  - vars: all
    varsIgnorePattern: "^_"
    args: after-used
    argsIgnorePattern: "^_"
  react/react-in-jsx-scope: 'off'
  react/prop-types: 'off'
  camelcase: error
  indent:
  - error
  - 2
  - SwitchCase: 1
    ignoredNodes:
    - ConditionalExpression
  no-duplicate-imports: error
  semi:
  - error
  - never
settings:
  import/resolver:
    typescript: {}
  react:
    version: detect
plugins:
- "@typescript-eslint"
- react
- react-hooks
- prettier
- unused-imports
